## File generated from pastele/cabi.h

module Kredki
  module Pastele
    extern 'int thorvg_engine_init(int engine_method, int threads)'
    extern 'int thorvg_engine_term(int engine_method)'
    extern 'void sdl_init(int joystick_enabled)'
    extern 'uint64_t sdl_get_ticks()'
    extern 'void clipboard_set_text(char* text)'
    extern 'char* clipboard_get_text( void)'
    extern 'void clipboard_get_mime_types( void(*consumer)(char*))'
    extern 'uint8_t keyboard_get_key_state(int keycode)'
    extern 'uint16_t keyboard_get_mod_state( void)'
    extern 'uint32_t mouse_get_button_state(int index)'
    extern 'void mouse_get_cursor_position(Point* point)'
    extern 'void mouse_set_capture(int set)'
    extern 'void* mouse_create_system_cursor(int cursor)'
    extern 'void mouse_set_cursor(SDL_Cursor* cursor)'
    extern 'uint32_t joystick_open(int index)'
    extern 'uint8_t joystick_get_button_state(int device_id, int button_index)'
    extern 'int16_t joystick_get_axis_value(int device_id, int axis_index)'
    extern 'void* application_new( void)'
    extern 'void application_delete(pastele::Application* self)'
    extern 'uint32_t application_insert_window(pastele::Application* self, pastele::Window* window)'
    extern 'uint32_t application_erase_window(pastele::Application* self, pastele::Window* window)'
    extern 'void application_set_event_handler(pastele::Application* self, int( *eventHandler)(int,  SDL_Event*))'
    extern 'void application_run(pastele::Application* self)'
    extern 'void application_exit(pastele::Application* self)'
    extern 'void* window_new_sw(int width, int height)'
    extern 'void* window_new_gl(int width, int height)'
    extern 'void window_delete(pastele::Window* self)'
    extern 'void window_close(pastele::Window* self)'
    extern 'void window_update_request(pastele::Window* self)'
    extern 'void window_update(pastele::Window* self, int needResize)'
    extern 'void window_show(pastele::Window* self)'
    extern 'void window_hide(pastele::Window* self)'
    extern 'void window_set_scene(pastele::Window* self, tvg::Scene* scene)'
    extern 'void window_paint_to_update(pastele::Window* self, tvg::Paint* paint)'
    extern 'void window_maximize(pastele::Window* self)'
    extern 'void window_minimize(pastele::Window* self)'
    extern 'void window_focus(pastele::Window* self)'
    extern 'void window_restore(pastele::Window* self)'
    extern 'void window_set_bordered(pastele::Window* self, int bordered)'
    extern 'void window_set_fullscreen(pastele::Window* self, int fullscreen)'
    extern 'void window_set_mouse_grab(pastele::Window* self, int grab)'
    extern 'int window_get_mouse_grab(pastele::Window* self)'
    extern 'void window_set_mouse_relative_mode(pastele::Window* self, int relative)'
    extern 'int window_get_mouse_relative_mode(pastele::Window* self)'
    extern 'void window_set_minimum_size(pastele::Window* self, int w, int h)'
    extern 'void window_set_maximum_size(pastele::Window* self, int w, int h)'
    extern 'void window_get_minimum_size(pastele::Window* self, IntPoint* point)'
    extern 'void window_get_maximum_size(pastele::Window* self, IntPoint* point)'
    extern 'void window_set_opacity(pastele::Window* self, float opacity)'
    extern 'float window_get_opacity(pastele::Window* self)'
    extern 'void window_set_position(pastele::Window* self, int x, int y)'
    extern 'void window_set_resizable(pastele::Window* self, int resizable)'
    extern 'void window_set_size(pastele::Window* self, int w, int h)'
    extern 'void window_set_title(pastele::Window* self, char* title)'
    extern 'const char* window_get_title(pastele::Window* self)'
    extern 'void window_set_always_on_top(pastele::Window* self, int on_top)'
    extern 'void window_get_size(pastele::Window* self, IntPoint* point)'
    extern 'void window_get_position(pastele::Window* self, IntPoint* point)'
    extern 'void window_set_text_input(pastele::Window* self, int input)'
    extern 'int window_get_text_input(pastele::Window* self)'
    extern 'int window_get_flags(pastele::Window* self)'
    extern 'void window_surface_to_png(pastele::Window* self, const char* file)'
    extern 'void window_get_display_bounds(pastele::Window* self, Bounds* bounds)'
    extern 'void window_get_pixel_color(pastele::Window* self, int x, int y, IntPoint* rg, IntPoint* ba)'
    extern 'void paint_delete(Paint* self)'
    extern 'void paint_set_transform(Paint* self, float pivot_x, float pivot_y, float x, float y, float a, float zoom_x, float fy)'
    extern 'void paint_set_opacity(Paint* self, uint8_t opacity)'
    extern 'void paint_get_bounds(Paint* self, Bounds* bounds)'
    extern 'void paint_set_clip(Paint* self, Shape* clipper)'
    extern 'void paint_set_mask(Paint* self, Paint* target, int mask)'
    extern 'void paint_set_blend_method(Paint* self, int method)'
    extern 'void paint_accessor_traverse(Paint* self, int(*callback)(const tvg::Paint* paint, void* data))'
    extern 'int paint_get_type(Paint* self)'
    extern 'void* shape_new( void)'
    extern 'void shape_delete(Shape* self)'
    extern 'void shape_reset(Shape* self)'
    extern 'void shape_move_to(Shape* self, float x, float y)'
    extern 'void shape_line_to(Shape* self, float x, float y)'
    extern 'void shape_cubic_to(Shape* self, float cx1, float cy1, float cx2, float cy2, float x, float y)'
    extern 'void shape_close(Shape* self)'
    extern 'void shape_append_rect(Shape* self, float x, float y, float w, float h)'
    extern 'void shape_append_circle(Shape* self, float cx, float cy, float rx, float ry)'
    extern 'void shape_append_round_rect(Shape* self, float x, float y, float w, float h, float corner_ss, float corner_se, float corner_es, float corner_ee)'
    extern 'void shape_set_stroke_width(Shape* self, float width)'
    extern 'void shape_set_stroke_color(Shape* self, uint8_t r, uint8_t g, uint8_t b, uint8_t a)'
    extern 'void shape_set_stroke_linear_gradient(Shape* self, float x, float y, float ex, float ey, const uint8_t* colors, const float* offsets, uint32_t cnt, int spread)'
    extern 'void shape_set_stroke_radial_gradient(Shape* self, float cx, float cy, float r, float fx, float fy, float fr, const uint8_t* colors, const float* offsets, uint32_t cnt, int spread)'
    extern 'void shape_set_stroke_dash(Shape* self, const float* dashPattern, uint32_t cnt, float offset)'
    extern 'void shape_set_stroke_cap(Shape* self, int cap)'
    extern 'void shape_set_stroke_join(Shape* self, int join)'
    extern 'void shape_set_stroke_miterlimit(Shape* self, float miterlimit)'
    extern 'void shape_set_stroke_trim(Shape* self, float begin, float end, int simultaneous)'
    extern 'void shape_set_fill_color(Shape* self, uint8_t r, uint8_t g, uint8_t b, uint8_t a)'
    extern 'void shape_set_fill_rule(Shape* self, int rule)'
    extern 'void shape_set_paint_order(Shape* self, int strokeFirst)'
    extern 'void shape_set_fill(Shape* self, Fill* fill)'
    extern 'void shape_set_fill_linear_gradient(Shape* self, float x, float y, float ex, float ey, const uint8_t* colors, const float* offsets, uint32_t cnt, int spread)'
    extern 'void shape_set_fill_radial_gradient(Shape* self, float cx, float cy, float r, float fx, float fy, float fr, const uint8_t* colors, const float* offsets, uint32_t cnt, int spread)'
    extern 'Picture* picture_new( void)'
    extern 'int picture_load(Picture* self, const char* path)'
    extern 'void picture_set_size(Picture* self, float w, float h)'
    extern 'void picture_get_size(Picture* self, Point* size)'
    extern 'void* picture_accessor_get(Picture* self, const char* id)'
    extern 'void* scene_new( void)'
    extern 'void scene_delete(Scene* self)'
    extern 'void scene_add(Scene* self, Paint* paint, Paint* at)'
    extern 'void scene_remove(Scene* self, Paint* paint)'
    extern 'void scene_clear_effects(Scene* self)'
    extern 'void scene_add_gaussian_blur(Scene* self, double sigma, int direction, int border, int quality)'
    extern 'void scene_add_drop_shadow(Scene* self, int r, int g, int b, int a, double angle, double distance, double blurSigma, int quality)'
    extern 'void scene_add_fill(Scene* self, int r, int g, int b, int a)'
    extern 'void scene_add_tint(Scene* self, int br, int bg, int bb, int wr, int wg, int wb, double intensity)'
    extern 'void scene_add_tritone(Scene* self, int sr, int sg, int sb, int mr, int mg, int mb, int hr, int hg, int hb, int blend)'
    extern 'void* text_new( void)'
    extern 'void text_delete(Text* self)'
    extern 'void text_set_font(Text* self, const char* fontName)'
    extern 'void text_set_size(Text* self, float size)'
    extern 'void text_set_text(Text* self, const char* text)'
    extern 'void text_set_fill_color(Text* self, uint8_t r, uint8_t g, uint8_t b)'
    extern 'void text_set_fill_linear_gradient(Text* self, float x, float y, float ex, float ey, const uint8_t* colors, const float* offsets, uint32_t cnt, int spread)'
    extern 'void text_set_fill_radial_gradient(Text* self, float cx, float cy, float r, float fx, float fy, float fr, const uint8_t* colors, const float* offsets, uint32_t cnt, int spread)'
    extern 'void text_set_outline(Text* self, float width, uint8_t r, uint8_t g, uint8_t b)'
    extern 'float text_get_text_width(Text* self, const char* text, int indexRequest)'
    extern 'int text_nearest_character_index(Text* self, const char* text, float widthRequest)'
    extern 'int font_load(const char* path)'
    extern 'int font_unload(const char* path)'
    extern 'Animation* animation_new( void)'
    extern 'void animation_set_frame(Animation* self, float no)'
    extern 'Paint* animation_get_picture(Animation* self)'
    extern 'float animation_get_total_frames(Animation* self)'
    extern 'float animation_get_duration(Animation* self)'
    extern 'void animation_set_segment(Animation* self, float begin, float end)'
    extern 'void animation_delete(Animation* self)'
  end
end
