require 'optparse'
require 'fileutils'
require_relative '../../lib-update-config'


def script_path file
  File.expand_path(file, File.dirname($0))
end

loader_file = File.new(script_path("../lib/kredki-core/abi/tvg.gen.rb"), "w")
loader_file.write <<~RUBY_
## File generated by lib-update.rb
## Manual changes not recommended

module Kredki
  module Abi
RUBY_

## Parse header file

classes = {}
classes.default_proc = proc{|h, k| h[k] = []}
pointer_type = proc{ _1.end_with? "*" }
File.new(CABI_HEADER).each_line do |line|
  if lm = /^\s*CABI\s+(.+)\s+(\w+)\((.*)\);/.match(line)
    parser = ""
    return_type = lm[1].strip
    case return_type
    when 'Tvg_Result'
      return_type = 'int'
    end
    # case return_type
    # when 'bool'
    #   return_type = 'int'
    # when pointer_type
    #   return_type = "void*"
    # end
    function_name = lm[2]
    attributes = lm[3].split(",").map do |attribute|
      attribute_tokens = attribute.split(" ").select{ _1 != "" }
      attribute_type = attribute_tokens[...-1].join " "
      # case attribute_type
      # when "Tvg_Engine", "unsigned"
      #   attribute_type = "int"
      # end
      "#{attribute_type} #{attribute_tokens[-1]}"
    end.join ", "
    loader_file.write "    extern '#{return_type} #{function_name}(#{attributes})'\n"
  end
end

loader_file.write "  end\nend\n"
loader_file.close
