require 'fileutils'
require_relative '../../lib-update-config'

loader_file = File.new File.expand_path("../lib/kredki-core/abi/tvg.gen.rb", File.dirname($0)), "w"
loader_file.write <<~EOS
## File generated by lib-update.rb
## Manual changes not recommended

module Kredki
  module Abi
EOS

## Parse header file

File.new(CABI_HEADER).each_line do |line|
  if lm = /^\s*CABI\s+(.+)\s+(\w+)\((.*)\);/.match(line)
    attributes = lm[3].split(",").map do |attribute|
      attribute_tokens = attribute.split(" ").select{ _1 != "" }
      attribute_type = attribute_tokens[...-1].join " "
      "#{attribute_type} #{attribute_tokens[-1]}"
    end.join ", "
    loader_file.write "    extern '#{lm[1].strip} #{lm[2]}(#{attributes})'\n"
  end
end

loader_file.write "  end\nend\n"
loader_file.close
